'use client';
import {useState} from 'react';
import {ArrowUp,ArrowDown,Printer,BookOpen,Leaf} from 'lucide-react';
import {canPublish,type Observation,type Collection} from '@/lib/domain';
export default function Book({observations,collections}:{observations:Observation[];collections:Collection[]}){
 const [collection,setCollection]=useState('all');const [title,setTitle]=useState('우리의 작은 자연 기록집');const [order,setOrder]=useState<string[]>([]);
 const eligible=observations.filter(o=>canPublish(o)&&(collection==='all'||o.sessionId===collection)).sort((a,b)=>{const ai=order.indexOf(a.id),bi=order.indexOf(b.id);return (ai<0?999:ai)-(bi<0?999:bi)});
 function move(index:number,delta:number){const ids=eligible.map(o=>o.id);[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];setOrder(ids);}
 return <section className="book-workspace"><div className="page-heading no-print"><div><span className="eyebrow">THE PUBLICATION</span><h1>관찰이 한 권의 책으로.</h1><p>검수와 동의가 완료된 기록만 이곳에 모입니다.</p></div><button className="button" disabled={!eligible.length||!title.trim()} onClick={()=>window.print()}><Printer size={18}/> 인쇄 · PDF 저장</button></div>
 <div className="book-layout"><aside className="book-settings no-print"><h2>기록집 설정</h2><label>표지 제목<input maxLength={80} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>수록 범위<select value={collection} onChange={e=>setCollection(e.target.value)}><option value="all">전체 컬렉션</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p className="hint">인쇄 창에서 ‘PDF로 저장’을 선택하세요. A4, 배경 그래픽 켜기, 머리글·바닥글 끄기를 권장합니다.</p><div className="book-count"><strong>{eligible.length}</strong><span>개의 검수된 기록</span></div><h3>수록 순서</h3>{eligible.map((o,i)=><div className="order-item" key={o.id}><span>{String(i+1).padStart(2,'0')} {o.title}</span><button className="icon-button" aria-label={`${o.title} 위로`} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={15}/></button><button className="icon-button" aria-label={`${o.title} 아래로`} disabled={i===eligible.length-1} onClick={()=>move(i,1)}><ArrowDown size={15}/></button></div>)}</aside>
 <div className="book-preview">{eligible.length?<><article className="book-cover"><div className="cover-top"><Leaf size={25}/><span>NATURE LENS<br/>FIELD JOURNAL</span></div><h2>{title||'기록집 제목'}</h2><p>가까이 들여다본 자연,<br/>오래 간직할 우리의 발견.</p><div className="cover-art"><Leaf strokeWidth={.5}/></div><footer><span>{new Date().getFullYear()} · {eligible.length} OBSERVATIONS</span><span>뉴리프 · NEW LEAF</span></footer></article>{eligible.map((o,i)=><article key={o.id} className="book-page"><header><span>NATURE LENS / FIELD NOTES</span><span>{String(i+1).padStart(2,'0')}</span></header><img src={o.photo} alt={o.title}/><div className="book-page-copy"><span className="eyebrow">{o.date} · {o.protection==='protected'?'보호 필요 · 위치 비공개':'위치 비공개'}</span><h2>{o.title}</h2><h3>{o.species} <em>{o.scientificName}</em></h3><p>{o.notes}</p>{o.habitat&&<p className="hint">서식 환경: {o.habitat}</p>}<footer>사람이 검수한 기록 · {o.aiAssisted?'AI 생성 내용 포함':'직접 작성'}{o.demo?' · 사용법 예제 / 가상 기록':''}</footer></div></article>)}</>:<div className="empty-state"><BookOpen size={48} strokeWidth={1}/><h2>책에 담을 기록을 기다려요</h2><p>관찰실에서 사진과 기록을 확인하고<br/>‘검수 완료로 저장’을 선택해 주세요.</p></div>}</div></div></section>;
}
