'use client';
import {useState,useEffect,useRef} from 'react';
import {Leaf,Plus,Search,Grid2X2,BookOpen,FolderOpen,Download,Upload,ArrowUpRight,ShieldCheck,Trash2,WifiOff,HardDrive,PanelLeftClose,X,Check,LoaderCircle} from 'lucide-react';
import {newObservation,canPublish,type Observation,type Collection} from '@/lib/domain';
import {readLibrary,saveObservation,deleteObservation,saveCollection} from '@/lib/storage';
import {createBackup,downloadBackupFile,restoreBackupFile,backupErrorMessage} from '@/lib/backup';
import {demoRecords} from '@/lib/demo';
import Editor from './Editor';import Book from './Book';
type View='library'|'collections'|'book'|'settings';
export default function Studio(){
 const [view,setView]=useState<View>('library');const [observations,setObservations]=useState<Observation[]>([]);const [collections,setCollections]=useState<Collection[]>([]);const [editor,setEditor]=useState<Observation|null>(null);const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [collection,setCollection]=useState('all');const [loading,setLoading]=useState(true);const [fatal,setFatal]=useState(false);const [message,setMessage]=useState('');const [offline,setOffline]=useState(false);const [newCollection,setNewCollection]=useState('');const [busy,setBusy]=useState(false);const importRef=useRef<HTMLInputElement>(null);
 const returnFocus=useRef<HTMLElement|null>(null);
 function openEditor(o:Observation){returnFocus.current=document.activeElement as HTMLElement;setEditor(o);}
 function closeEditor(){setEditor(null);requestAnimationFrame(()=>returnFocus.current?.focus());}
 async function reload(){const data=await readLibrary();setObservations(data.observations.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)));setCollections(data.collections);}
 useEffect(()=>{void reload().catch(()=>{setFatal(true);setMessage('저장소를 열지 못했습니다. 브라우저의 사이트 저장 권한을 확인한 뒤 새로고침해 주세요.');}).finally(()=>setLoading(false));const sync=()=>setOffline(!navigator.onLine);sync();window.addEventListener('online',sync);window.addEventListener('offline',sync);const visibility=()=>{if(document.visibilityState==='visible')void reload().catch(()=>setMessage('기록을 새로 불러오지 못했습니다.'));};document.addEventListener('visibilitychange',visibility);const base=process.env.NEXT_PUBLIC_BASE_PATH||'';if('serviceWorker' in navigator&&process.env.NODE_ENV==='production')void navigator.serviceWorker.register(`${base}/sw.js`).catch(()=>setMessage('오프라인 기능을 준비하지 못했습니다. 인터넷 연결 상태에서 다시 방문해 주세요.'));return()=>{window.removeEventListener('online',sync);window.removeEventListener('offline',sync);document.removeEventListener('visibilitychange',visibility);};},[]);
 const ready=observations.filter(canPublish).length;
 const shown=observations.filter(o=>(collection==='all'||o.sessionId===collection)&&(filter==='all'||(filter==='reviewed'?canPublish(o):!canPublish(o)))&&[o.title,o.species,o.notes].some(x=>x.toLowerCase().includes(query.toLowerCase())));
 async function save(o:Observation,expectedUpdatedAt:string|null){await saveObservation(o,expectedUpdatedAt);await reload();closeEditor();setMessage(o.status==='reviewed'?'검수를 완료했습니다. 기록집에 담을 수 있어요.':'초안을 저장했습니다.');}
 async function remove(o:Observation){if(!confirm(`‘${o.title}’ 기록을 삭제할까요? 삭제 전 백업을 권장합니다.`))return;try{await deleteObservation(o.id);await reload();setMessage('기록을 삭제했습니다.');}catch{setMessage('삭제하지 못했습니다. 다시 시도해 주세요.');}}
 async function demos(){setBusy(true);try{const existing=new Set(observations.map(o=>o.id));for(const o of demoRecords())if(!existing.has(o.id))await saveObservation(o,null);await reload();setMessage('가상 예제 3건을 불러왔습니다. 실제 관찰 자료가 아닙니다.');}catch{setMessage('예제를 저장하지 못했습니다. 저장 공간을 확인해 주세요.');}finally{setBusy(false);}}
 async function backup(){try{const {blob,filename}=await createBackup();downloadBackupFile(blob,filename);setMessage('백업 파일을 내려받았습니다. 사진과 기록이 포함됩니다.');}catch{setMessage('백업을 만들지 못했습니다. 다시 시도해 주세요.');}}
 async function restore(file?:File){if(!file)return;setBusy(true);try{const count=await restoreBackupFile(file);await reload();setMessage(`${count}건을 초안으로 복원했습니다. 중복 기록은 유지했고, 출판 전 다시 검수해 주세요.`);}catch(e){setMessage(backupErrorMessage(e));}finally{setBusy(false);if(importRef.current)importRef.current.value='';}}
 async function createCollection(e:React.FormEvent){e.preventDefault();const name=newCollection.trim();if(!name||busy)return;if(collections.some(c=>c.name===name)){setMessage('같은 이름의 컬렉션이 있습니다.');return;}setBusy(true);try{await saveCollection({id:crypto.randomUUID(),name});await reload();setNewCollection('');setMessage('컬렉션을 만들었습니다. 관찰 편집에서 기록을 연결하세요.');}catch(e){setMessage(e instanceof Error?e.message:'컬렉션을 저장하지 못했습니다.');}finally{setBusy(false);}}
 const nav=[{id:'library',label:'관찰실',icon:Grid2X2},{id:'collections',label:'컬렉션',icon:FolderOpen},{id:'book',label:'기록집 만들기',icon:BookOpen}] as const;
 return <div className="studio"><aside className="sidebar no-print"><a href="#main" className="brand" onClick={()=>setView('library')}><span className="brand-symbol"><Leaf size={24}/></span><span>nature lens<small>by NEW LEAF</small></span></a><div className="workspace-label">나의 기록 공간</div><nav aria-label="주 메뉴">{nav.map(n=><button key={n.id} className={view===n.id?'nav-item active':'nav-item'} aria-current={view===n.id?'page':undefined} onClick={()=>setView(n.id)}><n.icon size={19}/>{n.label}{n.id==='library'&&<span className="nav-count">{observations.length}</span>}</button>)}</nav><div className="sidebar-note"><Leaf size={25} strokeWidth={1.2}/><p>작은 발견이 모여<br/>오래 남을 이야기가 됩니다.</p><span>LOOK CLOSER. KEEP WONDERING.</span></div><div className="sidebar-bottom"><button className={view==='settings'?'nav-item active':'nav-item'} onClick={()=>setView('settings')}><HardDrive size={18}/> 저장과 백업</button><div className="local-state"><span className="status-dot"/> 이 브라우저에 저장 중</div></div></aside>
 <div className="main-shell"><header className="topbar no-print"><div className="breadcrumb">내 작업실 <span>/</span> {view==='library'?'관찰실':view==='collections'?'컬렉션':view==='book'?'기록집':'저장과 백업'}</div><div className="topbar-right">{offline?<span className="offline"><WifiOff size={14}/> 오프라인</span>:<button className="text-button local-label" onClick={()=>setView('settings')}><HardDrive size={14}/> 저장과 백업</button>}<span className="avatar">N</span></div></header>
 <main id="main" tabIndex={-1}>{loading?<div className="empty-state"><LoaderCircle className="spin"/><h1>관찰실을 불러오는 중</h1></div>:fatal?<div className="empty-state"><h1>브라우저 저장소에 연결할 수 없어요</h1><p>사이트 데이터 저장 권한을 허용한 뒤 다시 열어 주세요.</p><button className="button" onClick={()=>location.reload()}>다시 불러오기</button></div>:<>
 {view==='library'&&<><section className="welcome"><div className="welcome-copy"><span className="eyebrow">YOUR FIELD JOURNAL</span><h1>가까이 볼수록,<br/>새로운 세계.</h1><p>오늘 만난 자연을 기록하고,<br className="mobile-break"/> 우리의 기록집으로 엮어보세요.</p><button className="button" onClick={()=>openEditor(newObservation())}><Plus size={18}/> 관찰 기록하기</button></div><div className="welcome-art" aria-hidden="true"><div className="botanical-mark"><Leaf strokeWidth={.65}/></div><span className="art-caption">EVERY LEAF HAS A STORY.</span></div><div className="welcome-index"><span>자연을 보는 새로운 시선</span><span>NATURE LENS · NEW LEAF</span></div></section>
 <section className="library-section"><div className="section-heading"><h2>나의 관찰 <span>{observations.length}</span></h2><button className="text-button" onClick={()=>setView('book')}>기록집으로 엮기 <ArrowUpRight size={17}/></button></div><div className="library-toolbar"><div className="tabs" aria-label="기록 상태">{[{id:'all',text:'전체',count:observations.length},{id:'draft',text:'검수 대기',count:observations.length-ready},{id:'reviewed',text:'검수 완료',count:ready}].map(t=><button key={t.id} className={filter===t.id?'selected':''} aria-pressed={filter===t.id} onClick={()=>setFilter(t.id)}>{t.text}<span>{t.count}</span></button>)}</div><div className="search-filters"><select aria-label="컬렉션 필터" value={collection} onChange={e=>setCollection(e.target.value)}><option value="all">모든 컬렉션</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><label className="search"><Search size={16}/><input aria-label="관찰 검색" placeholder="기록 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label></div></div>
 {shown.length?<div className="observation-grid">{shown.map(o=><article className="observation-card" key={o.id}><button className="card-open" onClick={()=>openEditor(o)} aria-label={`${o.title} 편집`}><div className="card-image"><img src={o.photo} alt={o.title}/></div><div className="card-copy"><div className="card-meta"><span>{o.date.replaceAll('-','. ')}</span><span className={canPublish(o)?'badge reviewed':'badge'}>{canPublish(o)?'검수 완료':'검수 대기'}</span></div><h3>{o.title}</h3><p>{o.species||'식물 이름을 확인해 주세요'}</p></div></button><footer><span>{o.demo?'삽화 · 가상 예제':o.sessionId?collections.find(c=>c.id===o.sessionId)?.name||'컬렉션':'개인 관찰'}</span><button className="icon-button" aria-label={`${o.title} 삭제`} onClick={()=>void remove(o)}><Trash2 size={15}/></button></footer></article>)}<button className="add-card" onClick={()=>openEditor(newObservation())}><Plus size={28} strokeWidth={1}/><strong>다음 발견을 기다려요</strong><span>새 관찰 기록 추가</span></button></div>:<div className="empty-state library-empty"><Leaf size={42} strokeWidth={1}/><h3>{observations.length?'조건에 맞는 기록이 없어요':'첫 번째 발견을 남겨보세요'}</h3><p>{observations.length?'검색어나 필터를 바꿔 보세요.':'사진 한 장과 짧은 메모면 충분합니다.'}</p>{!observations.length&&<button className="text-button" disabled={busy} onClick={()=>void demos()}>먼저 예제 3건으로 둘러보기 <ArrowUpRight size={16}/></button>}</div>}
 <div className="privacy-foot"><ShieldCheck size={16}/><span>기록은 이 브라우저에 보관됩니다. 소중한 관찰은 정기적으로 백업해 주세요.</span><button className="text-button" onClick={()=>void backup()}>백업하기</button></div></section></>}
 {view==='book'&&<Book observations={observations} collections={collections}/>}
 {view==='collections'&&<section className="standard-page"><div className="page-heading"><div><span className="eyebrow">COLLECTIONS</span><h1>발견을 모으는 방법.</h1><p>산책, 계절, 캠프별로 기록을 묶어보세요. 이 브라우저에서만 보관됩니다.</p></div></div><form className="collection-form" onSubmit={createCollection}><label htmlFor="collection-name">새 컬렉션</label><div><input id="collection-name" value={newCollection} onChange={e=>setNewCollection(e.target.value)} maxLength={80} required placeholder="예: 가을 숲 산책"/><button className="button" disabled={busy||!newCollection.trim()}><Plus size={17}/> 만들기</button></div></form><div className="collections-grid">{collections.map(c=><button className="collection-card" key={c.id} onClick={()=>{setCollection(c.id);setQuery('');setFilter('all');setView('library');}}><FolderOpen size={34} strokeWidth={1}/><h2>{c.name}</h2><p>{observations.filter(o=>o.sessionId===c.id).length}개의 기록</p><ArrowUpRight size={19}/></button>)}</div>{!collections.length&&<div className="empty-state"><FolderOpen size={40} strokeWidth={1}/><h2>첫 컬렉션을 만들어보세요</h2><p>관찰 기록 편집에서 컬렉션을 지정할 수 있어요.</p></div>}</section>}
 {view==='settings'&&<section className="standard-page"><div className="page-heading"><div><span className="eyebrow">YOUR DATA</span><h1>기록은 온전히, 내 곁에.</h1><p>기본 기록은 이 브라우저에 보관됩니다. 모바일 공동 관찰을 연결한 경우 명시적으로 제출한 사본만 서버로 전송됩니다.</p></div></div><div className="settings-panel"><div><HardDrive size={28}/><h2>이 브라우저의 작업실</h2><p>관찰 {observations.length}건 · 컬렉션 {collections.length}개</p><p>사이트 데이터 삭제, 시크릿 창 종료, 기기 변경 시 기록이 사라질 수 있습니다. 백업 파일은 안전한 곳에 보관해 주세요.</p></div><div className="settings-actions"><button className="button" onClick={()=>void backup()}><Download size={18}/> 전체 백업 내려받기</button><button className="button secondary" disabled={busy} onClick={()=>importRef.current?.click()}><Upload size={18}/> 백업 복원하기</button><input hidden ref={importRef} type="file" accept="application/json,.json" onChange={e=>void restore(e.target.files?.[0])}/><p className="hint">Nature Lens JSON · 최대 50MB<br/>작업실 한도: 45MB · 500건 · 컬렉션 100개.<br/>중복 기록은 덮어쓰지 않습니다. 복원한 기록은 재검수가 필요합니다.</p></div></div><div className="settings-panel"><div><h2>현재 사용할 수 있는 기능</h2><p>사진 등록, 수동 편찬, 검수, 컬렉션, 기록집 PDF 저장, 오프라인 기록.</p><p>자동 AI 판별, 클라우드 동기화, QR 공동 참여는 아직 연결되지 않았습니다. 위치는 사용자가 선택한 경우에만 기록하며, 얼굴이 있는 사진은 출판 대상에서 제외합니다.</p></div><button className="button secondary" disabled={busy} onClick={()=>void demos()}>가상 예제 불러오기</button></div></section>}
 </>}</main><footer className="app-footer no-print"><span>nature lens <span className="muted"> / </span> 한 장의 사진이 한 권의 기록이 되기까지.</span><span>사단법인 뉴리프</span></footer></div>
 {message&&<div className="toast no-print" role="status"><span>{message}</span><button className="icon-button" aria-label="알림 닫기" onClick={()=>setMessage('')}><X size={17}/></button></div>}{editor&&<Editor record={editor} collections={collections} onSave={save} onClose={closeEditor}/>}
 </div>;
}
