'use client';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Leaf, MapPin, Printer } from 'lucide-react';
import { STORIES, GROUP_LABELS } from '@/lib/community';
const base=process.env.NEXT_PUBLIC_BASE_PATH||'';
export default function MonthlyJournal() {
 const [reading,setReading]=useState(false);
 if(reading)return <section className="j-reader"><div className="j-reader-tools"><button className="m-text" onClick={()=>setReading(false)}><ArrowLeft size={18}/> 저널 목록</button><button className="m-text" onClick={()=>window.print()}><Printer size={17}/> 인쇄 · PDF</button></div><article className="j-paper j-cover"><span className="j-imprint">nature lens / 월간 생명 저널</span><h1>작은 생명에게<br/>마음을 건네는 방법</h1><p>2026. 09 · 창간 구성 예시</p><img src={`${base}/community/butterfly.jpg`} alt="꽃 위의 나비를 표현한 AI 예시 이미지"/><p>눈길이 머문 자리에 이야기가 자랍니다.<br/>우리 곁의 작은 세계를 기록하는 사람들.</p><small>모든 사진·관찰자·에피소드는 예시입니다. 실제 발행본이 아닙니다.</small></article><article className="j-paper j-editorial"><Leaf size={28}/><h2>관찰은 마음을 쓰는 일</h2><p>꽃 앞에서 걸음을 늦추고, 나비에게 먼저 자리를 내어주고, 비가 지난 돌 위로 몸을 낮추는 일. 이 저널은 그런 작은 행동을 모으려 합니다.</p><p>많은 공감을 받은 사진 옆에는 조용히 쌓인 관찰도 놓습니다. 사람마다 다른 지역과 생명의 이야기가 만나면, 우리가 돌보고 싶은 자연의 모습도 더 넓어질 테니까요.</p><blockquote>자연을 복원하고 종 다양성을 지키는 일은, 먼저 그 생명을 알아보는 관심에서 시작됩니다.</blockquote><p className="j-editor-note">편집 방향 예시입니다. 관찰·공감 수는 생태 복원 성과를 입증하는 지표가 아닙니다.</p></article>{STORIES.map((s,i)=><article className="j-paper j-entry" key={s.id}><span className="j-imprint">{String(i+1).padStart(2,'0')} / {GROUP_LABELS[s.group]}와의 만남</span><h2>{s.title}</h2><p className="j-byline">{s.author} · {s.region} · {s.date}</p><img src={`${base}/community/${s.image}`} alt={`${s.species} AI 예시 이미지`}/><p>{s.story}</p><blockquote>{s.care}</blockquote><footer>예시 이야기 · AI 예시 이미지 · 종 미확정 · 정밀 위치 비공개</footer></article>)}<article className="j-paper j-closing"><h2>다음 달에도,<br/>같은 자리에서 만나기</h2><p>한 번의 사진에서 그치지 않고, 같은 곳을 천천히 다시 바라보세요. 달라진 색, 다시 찾아온 생명, 아직 이름을 모르는 존재를 기록해 주세요.</p><span>관찰 → 공감 → 이야기 → 다음 관찰</span></article></section>;
 return <section className="j-library"><div className="m-page-title"><span className="m-muted">우리의 발견이 한 권의 이야기로</span><h1>월간 생명 저널</h1><p>사진과 마음, 지역의 에피소드를 엮습니다.</p></div><div className="c-demo-note"><BookOpen size={16}/><span>예시 9월호 · 실제 정기 발행은 연결 전입니다.</span></div><button className="j-issue" onClick={()=>{setReading(true);window.scrollTo(0,0);}}><div className="j-issue-cover"><span>nature lens</span><h2>작은 생명에게<br/>마음을 건네는 방법</h2><img src={`${base}/community/butterfly.jpg`} alt="9월호 AI 예시 표지"/><span>2026. 09 / 월간 생명 저널</span></div><div className="j-issue-summary"><strong>9월, 우리가 눈길을 건넨 생명들</strong><span>식물과 곤충 · 3개의 예시 이야기 <ArrowRight size={18}/></span></div></button><button className="m-primary" onClick={()=>{setReading(true);window.scrollTo(0,0);}}><BookOpen size={18}/> 9월호 미리 읽기</button><section className="j-principles"><h2>좋아요 너머의 이야기도 담아요</h2><p>공감을 모은 사진, 지역마다 다른 발견, 식물과 곤충의 다양한 만남을 함께 살핍니다. 검수와 출판 동의를 마친 기록만 실제 저널에 실립니다.</p><div><HeartIcon/> 공감 · <MapPin size={15}/> 지역 · <Leaf size={15}/> 다양성</div></section></section>;
}
function HeartIcon(){return <span aria-hidden="true">♡</span>;}
